RNS Shell Implementation
react-native-skia/react-native-skia pull request #15
Opened 2021-06-01 17:41 UTC by munezbn

Implemented RNS Shell for replacing sk_app which was used from Skia for POC purpose.
Supports Only Linux Platform now.
Has Boot strap code for application.
Has platform Task runner implementation.
Has Layer management and Render Tree management.
Has Platform Graphics support with OpenGL backend with X11 & LibWPE client backend. Supports GLX and EGL interface.
Has compositor framework for rendering Render Layer tree.

Added RNS logging and Utility Helper Macros.

2021-06-06 15:02 UTC, Kudo requested changes
if sk_app is not used, please try to remove sk_app, so that git may able to know the file renaming. otherwise, it's hard to review the difference between sk_app and rns_shell.

2021-06-06 15:02 UTC, Kudo commented on ReactSkia/BUILD.gn
> +     "//rns_shell/platform/graphics/gl",
could use `public_configs` in rns_shell. something like the
https://github.com/Kudo/react-native-skia/blob/f0b100c12acd0c934ba32f213601df90c8c685b9/build/secondary/react-native/ReactCommon/yoga/BUILD.gn#L34

2021-06-08 04:55 UTC, munezbn commented on ReactSkia/BUILD.gn
> +     "//rns_shell/platform/graphics/gl",
Done.

2021-06-08 04:58 UTC, munezbn commented
> if sk_app is not used, please try to remove sk_app, so that git may able to know the file renaming. otherwise, it's hard to review the difference between sk_app and rns_shell.

Done, But I noticed that git didn't detect all the files as renamed, some of file still shown as new files. But it is better than before.

2021-06-18 09:13 UTC, Kudo approved these changes
LGTM 🚀

2021-06-18 09:14 UTC, merged