Added support for Text Props
react-native-skia/react-native-skia pull request #37
Opened 2022-01-12 11:10 UTC by martunjai

Added Support for Text Properties:

- fontColor
- fontfamily
- fontSize
- fontStyle
- fontWeight
- textDecorationLine
- textShadowOffset
- textShadowRadius
- letterSpacing
- lineHeight
- numberofLines
- ellipSizeMode - Clip, Tail 
- backgroundColor

2022-01-22 13:55 UTC, Kudo approved these changes
looks promising 🔥

2022-01-23 06:35 UTC, pprabhu-ng approved these changes

2022-03-30 14:04 UTC, pprabhu-ng requested changes

2022-03-30 14:04 UTC, pprabhu-ng commented on ReactSkia/components/RSkComponentText.cpp
> +void RSkComponentParagraph::updateComponentProps(const ShadowView &newShadowView,bool forceUpadte) {
looks like this is duplicate definition of the api.

2022-11-02 06:20 UTC, pprabhu-ng commented
Closing this PR as the changes are already merged as part of https://github.com/react-native-skia/react-native-skia/commit/1ae5b429fe0cd078c7f51b74fb1dbac02ccee80f

2022-11-02 06:20 UTC, closed without merging